feat(marketplace-benchmark-refactor): working now
Acurast/acurast-core pull request #33
Opened 2022-12-09 16:28 UTC by JuaniRios

2022-12-13 13:11 UTC, gitsimon requested changes

2022-12-13 13:11 UTC, gitsimon commented on pallets/marketplace/src/types.rs
> +pub type AssetAmount = u128;
Is there no way to avoid having concrete types in non benchmarking code, and rather move it to stub.rs that is only included with benchmarking flag ?

2022-12-13 13:11 UTC, gitsimon commented on pallets/marketplace/src/lib.rs
> +            + From<u128>;
remove duplicate trait bound

2022-12-13 13:11 UTC, gitsimon commented on pallets/marketplace/src/lib.rs
> +        type Reward: IsType<RewardFor<Self>> + From<MinimumAssetImplementation>;
Similar: why is this now in non benchmarking code?

2022-12-15 15:41 UTC, closed without merging

2022-12-15 15:42 UTC, JuaniRios commented
changes rebased by feat/acurast-benchmark-refactor