feat/required-modules
Acurast/acurast-core pull request #69
Opened 2023-03-22 15:34 UTC by godenzim

… for a job and available modules for a processor

2023-03-23 13:20 UTC, RomarQ approved these changes
`registration_payload_schema` needs to be updated to include the new `required_modules` field. I am surprised the tests did not need to be updated.

2023-03-24 09:09 UTC, gitsimon requested changes

2023-03-24 09:09 UTC, gitsimon commented on pallets/marketplace/src/functions.rs
> +impl<T: Config> Pallet<T> {
Maybe move the other functions under `impl<T: Config> Pallet<T>` in `lib.rs` here too?

2023-03-28 07:15 UTC, RomarQ approved these changes

2023-03-28 07:39 UTC, merged